name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-graalvm@1.0
      with:
        graalvm-version: '19.2.1'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: native-image
      run: |
        mkdir dist
        gu install native-image
        ./mvnw package -Pgraal
        cp target/classes/rsc* ./rsc
        cp target/classes/rsc* ./dist/
        ./mvnw package -Dversion.generate.skip=true -DskipTests
        cp target/rsc*.jar ./dist/
    - name: check-cli
      run: |        
        ./rsc --version
        ./rsc ws://rsocket-demo.herokuapp.com/rsocket --route searchTweets --stream -d Trump --take 3 --debug
        ./rsc wss://rsocket-demo.herokuapp.com/rsocket --route searchTweets --stream -d Trump --take 3 --debug
    - name: upload-dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
